Imports GTA
Imports GTA.Native.Function

Public Class NativePTFX
    Private _ptfxHandle As Integer
    Private _fxHashName As String
    Private _pos As Vector3
    Private _rot As Vector3
    Public ReadOnly Property Handle As Integer
        Get
            Return _ptfxHandle
        End Get
    End Property
    Public ReadOnly Property FxName As String
        Get
            Return _fxHashName
        End Get
    End Property
    Public Property Position As Vector3
        Get
            Return _pos
        End Get
        Set(value As Vector3)
            [Call]("UPDATE_PTFX_OFFSETS", _ptfxHandle, value.X, value.Y, value.Z, _rot.X, _rot.Y, _rot.Z)
            _pos = value
        End Set
    End Property
    Public Property Rotation As Vector3
        Get
            Return _rot
        End Get
        Set(value As Vector3)
            [Call]("UPDATE_PTFX_OFFSETS", _ptfxHandle, _pos.X, _pos.Y, _pos.Z, value.X, value.Y, value.Z)
            _rot = value
        End Set
    End Property
    Public Sub New(ParticleFx As String)
        _fxHashName = ParticleFx

        ' _ptfxHandle = StartPTFX(ParticleFx, New Vector3(0, 0, 0), New Vector3(0, 0, 0), 0.000000001)
        '  StopPTFX(_ptfxHandle)
    End Sub
    Public Sub Evolve(Optional Effect As String = "fade", Optional Value As Single = 0)
        [Call]("EVOLVE_PTFX", _ptfxHandle, Effect, Value)
    End Sub
    Public Function Exists() As Boolean
        If _ptfxHandle <> 0 Then Return True Else Return False
    End Function
    Public Sub Start(Position As Vector3, Rotation As Vector3, FxScale As Single)
        _ptfxHandle = [Call](Of Integer)("START_PTFX", _fxHashName.ToString, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Sub
    Public Sub StartOnVehicle(Car As Vehicle, Position As Vector3, Rotation As Vector3, FxScale As Single)
        _ptfxHandle = [Call](Of Integer)("START_PTFX_ON_VEH", _fxHashName.ToString, Car, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Sub
    Public Sub StartOnObject(Obj As GTA.Object, Position As Vector3, Rotation As Vector3, FxScale As Single)
        _ptfxHandle = [Call](Of Integer)("START_PTFX_ON_OBJ", _fxHashName.ToString, Obj, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Sub
    Public Sub StartOnPed(Ped As GTA.Ped, Position As Vector3, Rotation As Vector3, FxScale As Single)
        _ptfxHandle = [Call](Of Integer)("START_PTFX_ON_PED", _fxHashName.ToString, Ped, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Sub
    Public Sub StartOnPedBone(Ped As GTA.Ped, Position As Vector3, Rotation As Vector3, BoneID As Bone, FxScale As Single)
        _ptfxHandle = [Call](Of Integer)("START_PTFX_ON_PED_BONE", _fxHashName.ToString, Ped, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, BoneID, FxScale)
    End Sub
    Public Sub [Stop]()
        [Call]("STOP_PTFX", _ptfxHandle)
        _ptfxHandle = 0
    End Sub
    Public Shared Function StartPTFX(PTFX As String, Position As Vector3, Rotation As Vector3, FxScale As Single) As Integer
        Return [Call](Of Integer)("START_PTFX", PTFX.ToString, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Function
    Public Shared Function StartPTFXOnVehicle(PTFX As String, Car As Vehicle, Position As Vector3, Rotation As Vector3, FxScale As Single) As Integer
        Return [Call](Of Integer)("START_PTFX_ON_VEH", PTFX.ToString, Car, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Function
    Public Shared Function StartPTFXOnObject(PTFX As String, Obj As GTA.Object, Position As Vector3, Rotation As Vector3, FxScale As Single) As Integer
        Return [Call](Of Integer)("START_PTFX_ON_OBJ", PTFX.ToString, Obj, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Function
    Public Shared Function StartPTFXOnPed(PTFX As String, Ped As GTA.Ped, Position As Vector3, Rotation As Vector3, FxScale As Single) As Integer
        Return [Call](Of Integer)("START_PTFX_ON_PED", PTFX.ToString, Ped, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Function
    Public Shared Function StartPTFXOnPedBone(PTFX As String, Ped As GTA.Ped, Position As Vector3, Rotation As Vector3, BoneID As Bone, FxScale As Single) As Integer
        Return [Call](Of Integer)("START_PTFX_ON_PED_BONE", PTFX.ToString, Ped, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, BoneID, FxScale)
    End Function
    Public Shared Sub EvolvePTFX(PTFX As Integer, Optional Effect As String = "fade", Optional Value As Single = 0)
        [Call]("EVOLVE_PTFX", PTFX, Effect, Value)
    End Sub
    Public Shared Sub StopPTFX(PTFX As Integer)
        [Call]("STOP_PTFX", PTFX)
    End Sub
    Public Shared Sub TriggerPTFX(PTFX As String, Position As Vector3, Rotation As Vector3, FxScale As Single)
        [Call]("TRIGGER_PTFX", PTFX.ToString, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Sub
    Public Shared Sub TriggerPTFXOnVehicle(PTFX As String, Car As Vehicle, Position As Vector3, Rotation As Vector3, FxScale As Single)
        [Call](Of Integer)("TRIGGER_PTFX_ON_VEH", PTFX.ToString, Car, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Sub
    Public Shared Sub TriggerPTFXOnObject(PTFX As String, Obj As GTA.Object, Position As Vector3, Rotation As Vector3, FxScale As Single)
        [Call](Of Integer)("TRIGGER_PTFX_ON_OBJ", PTFX.ToString, Obj, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Sub
    Public Shared Sub TriggerPTFXOnPed(PTFX As String, Ped As GTA.Ped, Position As Vector3, Rotation As Vector3, FxScale As Single)
        [Call](Of Integer)("TRIGGER_PTFX_ON_PED", PTFX.ToString, Ped, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, FxScale)
    End Sub
    Public Shared Sub TriggertPTFXOnPedBone(PTFX As String, Ped As GTA.Ped, Position As Vector3, Rotation As Vector3, BoneID As Bone, FxScale As Single)
        [Call](Of Integer)("TRIGGER_PTFX_ON_PED_BONE", PTFX.ToString, Ped, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z, BoneID, FxScale)
    End Sub
    Public Shared Sub UpdatePTFXOffsets(PTFX As Integer, Position As Vector3, Rotation As Vector3)
        [Call]("UPDATE_PTFX_OFFSETS", PTFX, Position.X, Position.Y, Position.Z, Rotation.X, Rotation.Y, Rotation.Z)
    End Sub
    '-----------------------------------------------------------------------------------------------------------------------------------------------------------------
    Public Structure ParticleFXs
        Public Const AmbientAshtraySmoke As String = "ambient_ashtray_smoke"
        Public Const AmbientButterflies As String = "ambient_butterflies"
        Public Const AmbientButterfliesB As String = "ambient_butterflies_b"
        Public Const AmbientCeilingDust As String = "ambient_ceiling_dust"
        Public Const AmbientCeilingSpawned As String = "ambient_ceiling_spawned"
        Public Const AmbientChemicalDrips As String = "ambient_chemical_drips"
        Public Const AmbientCigClouds As String = "ambient_cig_clouds"
        Public Const AmbientCigSmoke As String = "ambient_cig_smoke"
        Public Const AmbientCockroaches As String = "ambient_cockroaches"
        Public Const AmbientDryIce As String = "ambient_dry_ice"
        Public Const AmbientDustLitWindows As String = "ambient_dust_lit_windows"
        Public Const AmbientDustWindy As String = "ambient_dust_windy"
        Public Const AmbientElectricalSparks As String = "ambient_electrical_sparks"
        Public Const AmbientFireFlames As String = "ambient_fire_flames"
        Public Const AmbientFireGeneric As String = "ambient_fire_generic"
        Public Const AmbientFireGlow As String = "ambient_fire_glow"
        Public Const AmbientFireSmoke As String = "ambient_fire_smoke"
        Public Const AmbientFliesCircling As String = "ambient_flies_circling"
        Public Const AmbientFliesGlow As String = "ambient_flies_glow"
        Public Const AmbientFliesSmoke As String = "ambient_flies_smoke"
        Public Const AmbientFliesSparked As String = "ambient_flies_sparked"
        Public Const AmbientFliesSparks As String = "ambient_flies_sparks"
        Public Const AmbientFliesSpawner As String = "ambient_flies_spawner"
        Public Const AmbientFliesZapped As String = "ambient_flies_zapped"
        Public Const AmbientHornBlast As String = "ambient_horn_blast"
        Public Const AmbientHornSteam As String = "ambient_horn_steam"
        Public Const AmbientHotdogstand As String = "ambient_hotdogstand"
        Public Const AmbientHotTub As String = "ambient_hot_tub"
        Public Const AmbientLeavesWindy As String = "ambient_leaves_windy"
        Public Const AmbientOilDrips As String = "ambient_oil_drips"
        Public Const AmbientOverpassDebris As String = "ambient_overpass_debris"
        Public Const AmbientOverpassSpawned As String = "ambient_overpass_spawned"
        Public Const AmbientReceiptsWindy As String = "ambient_receipts_windy"
        Public Const AmbientReceiptsWindy3d As String = "ambient_receipts_windy_3d"
        Public Const AmbientResprayCan As String = "ambient_respray_can"
        Public Const AmbientRubbishWindy As String = "ambient_rubbish_windy"
        Public Const AmbientSandWindy As String = "ambient_sand_windy"
        Public Const AmbientSewerageFlows As String = "ambient_sewerage_flows"
        Public Const AmbientSewerageSinks As String = "ambient_sewerage_sinks"
        Public Const AmbientSteamChimney As String = "ambient_steam_chimney"
        Public Const AmbientSteamCold As String = "ambient_steam_cold"
        Public Const AmbientSteamCooking As String = "ambient_steam_cooking"
        Public Const AmbientSteamExhaust As String = "ambient_steam_exhaust"
        Public Const AmbientSteamManhole As String = "ambient_steam_manhole"
        Public Const AmbientSteamVent As String = "ambient_steam_vent"
        Public Const AmbientSteamVentOblong As String = "ambient_steam_vent_oblong"
        Public Const AmbientTowerPlumeLarge As String = "ambient_tower_plume_large"
        Public Const AmbientTowerPlumeSmall As String = "ambient_tower_plume_small"
        Public Const AmbientWaterDrips As String = "ambient_water_drips"
        Public Const AmbientWaterDripsInt As String = "ambient_water_drips_int"
        Public Const AmbientWaterPipeDrips As String = "ambient_water_pipe_drips"
        Public Const AmbientCeilingAreaSpawns As String = "amb_ceiling_area_spawns"
        Public Const AmbCeilingChunks As String = "amb_ceiling_chunks"
        Public Const AmbCeilingDust As String = "amb_ceiling_dust"
        Public Const AmbCeilingSilt As String = "amb_ceiling_silt"
        Public Const AmbLeavesWindy As String = "amb_leaves_windy"
        Public Const AmbOverpassAreaSpawns As String = "amb_overpass_area_spawns"
        Public Const AmbOverpassChunks As String = "amb_overpass_chunks"
        Public Const AmbOverpassDust As String = "amb_overpass_dust"
        Public Const AmbOverpassSilt As String = "amb_overpass_silt"
        Public Const AmbPlaneEngines As String = "amb_plane_engines"
        Public Const AmbReceiptsWindy As String = "amb_receipts_windy"
        Public Const AmbRubbishWindy As String = "amb_rubbish_windy"
        Public Const AmbShipPlume As String = "amb_ship_plume"
        Public Const AmbShipWhitesmoke As String = "amb_ship_whitesmoke"
        Public Const AmbSteamChimney As String = "amb_steam_chimney"
        Public Const AmbSteamCooking As String = "amb_steam_cooking"
        Public Const AmbSteamExhaust As String = "amb_steam_exhaust"
        Public Const AmbSteamManhole As String = "amb_steam_manhole"
        Public Const AmbTowerPlumeLg As String = "amb_tower_plume_lg"
        Public Const AmbTowerPlumeSm As String = "amb_tower_plume_sm"
        Public Const AnimHammerDebris As String = "anim_hammer_debris"
        Public Const AnimHammerDirt As String = "anim_hammer_dirt"
        Public Const AnimHammerDust As String = "anim_hammer_dust"
        Public Const AnimHammerSpecks As String = "anim_hammer_specks"
        Public Const AnimPneumatic As String = "anim_pneumatic"
        Public Const AnimPneumaticDust As String = "anim_pneumatic_dust"
        Public Const AnimPneumaticSpecks As String = "anim_pneumatic_specks"
        Public Const AnimRakeLeaves As String = "anim_rake_leaves"
        Public Const AnimSweepDust As String = "anim_sweep_dust"
        Public Const AnimWateringCan As String = "anim_watering_can"
        Public Const BangBlood As String = "bang_blood"
        Public Const BangCarmetal As String = "bang_carmetal"
        Public Const BangCarmetalDust As String = "bang_carmetal_dust"
        Public Const BangConcrete As String = "bang_concrete"
        Public Const BangConcreteDust As String = "bang_concrete_dust"
        Public Const BangDusty As String = "bang_dusty"
        Public Const BangGlass As String = "bang_glass"
        Public Const BangGrass As String = "bang_grass"
        Public Const BangGravel As String = "bang_gravel"
        Public Const BangGravelDust As String = "bang_gravel_dust"
        Public Const BangLeaves As String = "bang_leaves"
        Public Const BangMudSoft As String = "bang_mud_soft"
        Public Const BangMudSplashes As String = "bang_mud_splashes"
        Public Const BangSand As String = "bang_sand"
        Public Const BangWood As String = "bang_wood"
        Public Const BarkChunksSheet As String = "bark_chunks_sheet"
        Public Const BloodArteryMist As String = "blood_artery_mist"
        Public Const BloodBangChunks As String = "blood_bang_chunks"
        Public Const BloodFallChunks As String = "blood_fall_chunks"
        Public Const BloodGunChunks As String = "blood_gun_chunks"
        Public Const BloodGunEntry As String = "blood_gun_entry"
        Public Const BloodGunEntryArterial As String = "blood_gun_entry_arterial"
        Public Const BloodGunExit As String = "blood_gun_exit"
        Public Const BloodGunExitArterial As String = "blood_gun_exit_arterial"
        Public Const BloodMeleeBlunt As String = "blood_melee_blunt"
        Public Const BloodMeleeFluid As String = "blood_melee_fluid"
        Public Const BloodMeleeSharp As String = "blood_melee_sharp"
        Public Const BloodMeleeSharpIg As String = "blood_melee_sharp_ig"
        Public Const BloodMouthChunks As String = "blood_mouth_chunks"
        Public Const BloodMouthMist As String = "blood_mouth_mist"
        Public Const BloodScrapeMist As String = "blood_scrape_mist"
        Public Const BloodSharpCloud As String = "blood_sharp_cloud"
        Public Const BloodSharpFluid As String = "blood_sharp_fluid"
        Public Const BloodShotgunEntry As String = "blood_shotgun_entry"
        Public Const BloodShotgunExit As String = "blood_shotgun_exit"
        Public Const BloodShotgunMist As String = "blood_shotgun_mist"
        Public Const BloodSniperEntry As String = "blood_sniper_entry"
        Public Const BloodSniperExit As String = "blood_sniper_exit"
        Public Const BloodSniperMist As String = "blood_sniper_mist"
        Public Const BloodStunPunch As String = "blood_stun_punch"
        Public Const BloodWheelSquash As String = "blood_wheel_squash"
        Public Const BreakCardboard As String = "break_cardboard"
        Public Const BreakCardFlaps As String = "break_card_flaps"
        Public Const BreakCardSmallChunks As String = "break_card_small_chunks"
        Public Const BreakCardSmallSlivers As String = "break_card_small_slivers"
        Public Const BreakCeramic As String = "break_ceramic"
        Public Const BreakCeramicBits As String = "break_ceramic_bits"
        Public Const BreakCeramicDots As String = "break_ceramic_dots"
        Public Const BreakCeramicDust As String = "break_ceramic_dust"
        Public Const BreakCeramicSlabs As String = "break_ceramic_slabs"
        Public Const BreakDinoBones As String = "break_dino_bones"
        Public Const BreakDrugsCloud As String = "break_drugs_cloud"
        Public Const BreakDrugsJarDots As String = "break_drugs_jar_dots"
        Public Const BreakElectrical As String = "break_electrical"
        Public Const BreakElectricalDust As String = "break_electrical_dust"
        Public Const BreakElectricalFireLg As String = "break_electrical_fire_lg"
        Public Const BreakElectricalFireSm As String = "break_electrical_fire_sm"
        Public Const BreakElectricalGlow As String = "break_electrical_glow"
        Public Const BreakElectricalSparks As String = "break_electrical_sparks"
        Public Const BreakLaundryBasket As String = "break_laundry_basket"
        Public Const BreakLaundrySocks1 As String = "break_laundry_socks_1"
        Public Const BreakMetal As String = "break_metal"
        Public Const BreakMetalDust As String = "break_metal_dust"
        Public Const BreakMetalShards As String = "break_metal_shards"
        Public Const BreakMetalSlivers As String = "break_metal_slivers"
        Public Const BreakMetalSparks As String = "break_metal_sparks"
        Public Const BreakPlasterboard As String = "break_plasterboard"
        Public Const BreakSparks As String = "break_sparks"
        Public Const BreakSparksDust As String = "break_sparks_dust"
        Public Const BreakSparksFast As String = "break_sparks_fast"
        Public Const BreakSparksGlow As String = "break_sparks_glow"
        Public Const BreakSPAWNFire As String = "break_SPAWN_fire"
        Public Const BreakStone As String = "break_stone"
        Public Const BreakStoneBits As String = "break_stone_bits"
        Public Const BreakStoneDots As String = "break_stone_dots"
        Public Const BreakStoneDust As String = "break_stone_dust"
        Public Const BreakStoneSlabs As String = "break_stone_slabs"
        Public Const BreakWaterBarrel As String = "break_water_barrel"
        Public Const BreakWaterBarrelCore As String = "break_water_barrel_core"
        Public Const BreakWaterBarrelSplash As String = "break_water_barrel_splash"
        Public Const BreakWood As String = "break_wood"
        Public Const BreakWoodChunks As String = "break_wood_chunks"
        Public Const BreakWoodPlanks As String = "break_wood_planks"
        Public Const BreakWoodShards As String = "break_wood_shards"
        Public Const ColBinBitsMax10 As String = "col_bin_bits_max10"
        Public Const ColBinBitsMax25 As String = "col_bin_bits_max25"
        Public Const ColBinBitsMax5 As String = "col_bin_bits_max5"
        Public Const ColBinBitsMax50 As String = "col_bin_bits_max50"
        Public Const ColBinFastfoodChips As String = "col_bin_fastfood_chips"
        Public Const ColBinFastfoodCups As String = "col_bin_fastfood_cups"
        Public Const ColBinFastfoodLids As String = "col_bin_fastfood_lids"
        Public Const ColBinFastfoodNapkins As String = "col_bin_fastfood_napkins"
        Public Const ColBinGunkSplash As String = "col_bin_gunk_splash"
        Public Const ColBinHouseholdApple3 As String = "col_bin_household_apple3"
        Public Const ColBinHouseholdBanana8 As String = "col_bin_household_banana8"
        Public Const ColBinHouseholdFagp2 As String = "col_bin_household_fagp2"
        Public Const ColBinHouseholdPaper As String = "col_bin_household_paper"
        Public Const ColBinStreetBanana8 As String = "col_bin_street_banana8"
        Public Const ColDumpstersCardboard As String = "col_dumpsters_cardboard"
        Public Const ColDumpstersPaint As String = "col_dumpsters_paint"
        Public Const ColDumpstersPaper As String = "col_dumpsters_paper"
        Public Const ColDumpstersSlabs As String = "col_dumpsters_slabs"
        Public Const ColDumpstersWood As String = "col_dumpsters_wood"
        Public Const ColElectrical As String = "col_electrical"
        Public Const ColElectricalArcexpArc As String = "col_electrical_arcexp_arc"
        Public Const ColElectricalArcexpDust As String = "col_electrical_arcexp_dust"
        Public Const ColElectricalArcexpGlow As String = "col_electrical_arcexp_glow"
        Public Const ColElectricalArcing As String = "col_electrical_arcing"
        Public Const ColFastfoodNuts As String = "col_fastfood_nuts"
        Public Const ColFruitpileApples As String = "col_fruitpile_apples"
        Public Const ColFruitpileBananas As String = "col_fruitpile_bananas"
        Public Const ColFruitpileMix As String = "col_fruitpile_mix"
        Public Const ColFruitpileOranges As String = "col_fruitpile_oranges"
        Public Const ColLeavesAutumnal As String = "col_leaves_autumnal"
        Public Const ColLeavesPale As String = "col_leaves_pale"
        Public Const ColMailBundle As String = "col_mail_bundle"
        Public Const ColNapkins As String = "col_napkins"
        Public Const ColNewspaperBundle As String = "col_newspaper_bundle"
        Public Const ColSodaCansEcola As String = "col_soda_cans_ecola"
        Public Const ColSodaCansGinger As String = "col_soda_cans_ginger"
        Public Const ColSodaCansLemon As String = "col_soda_cans_lemon"
        Public Const ColSodaCansMix As String = "col_soda_cans_mix"
        Public Const ColSodaCansSprunk As String = "col_soda_cans_sprunk"
        Public Const CSBloodSawMist As String = "CS_blood_saw_mist"
        Public Const CSBlowtorchCore As String = "CS_blowtorch_core"
        Public Const CSBlowtorchGlow As String = "CS_blowtorch_glow"
        Public Const CSBurnBoxFlames As String = "CS_burn_box_flames"
        Public Const CSBurnBoxSmoke As String = "CS_burn_box_smoke"
        Public Const CSCabaretDryIce As String = "CS_cabaret_dry_ice"
        Public Const CSCabbitChunksB As String = "CS_cabbit_chunks_B"
        Public Const CSCabbitChunksF As String = "CS_cabbit_chunks_F"
        Public Const CSCabbitMistB As String = "CS_cabbit_mist_B"
        Public Const CSCabbitMistF As String = "CS_cabbit_mist_F"
        Public Const CSChestChunksB As String = "CS_chest_chunks_B"
        Public Const CSChestChunksF As String = "CS_chest_chunks_F"
        Public Const CSChinChunksB As String = "CS_chin_chunks_B"
        Public Const CSChinChunksF As String = "CS_chin_chunks_F"
        Public Const CSClarenceMistB As String = "CS_clarence_mist_B"
        Public Const CSClarenceMistF As String = "CS_clarence_mist_F"
        Public Const CSDimitriBrainB As String = "CS_dimitri_brain_B"
        Public Const CSDimitriMistB As String = "CS_dimitri_mist_B"
        Public Const CSDimitriMistF As String = "CS_dimitri_mist_F"
        Public Const CSEndBloodDrool As String = "CS_end_blood_drool"
        Public Const CSExecutionBlood As String = "CS_execution_blood"
        Public Const CSExecutionChest As String = "CS_execution_chest"
        Public Const CSExecutionChin As String = "CS_execution_chin"
        Public Const CSExecutionEye As String = "CS_execution_eye"
        Public Const CSExecutionIncar As String = "CS_execution_incar"
        Public Const CSFau7aCigarSmoke As String = "CS_Fau7a_cigar_smoke"
        Public Const CSFau7aLingeringSmoke As String = "CS_Fau7a_lingering_smoke"
        Public Const CSFaustinMistB As String = "CS_faustin_mist_B"
        Public Const CSFaustinMistF As String = "CS_faustin_mist_F"
        Public Const CSFoodSplatter As String = "CS_food_splatter"
        Public Const CSGT02DryIce As String = "CS_GT02_dry_ice"
        Public Const CSIncarBrainB As String = "CS_incar_brain_B"
        Public Const CSIncarChunksB As String = "CS_incar_chunks_B"
        Public Const CSIncarChunksF As String = "CS_incar_chunks_F"
        Public Const CSInteriorSmoke As String = "CS_interior_smoke"
        Public Const CSKneecapsMistB As String = "CS_kneecaps_mist_B"
        Public Const CSKneecapsMistF As String = "CS_kneecaps_mist_F"
        Public Const CSLighterFlame As String = "CS_lighter_flame"
        Public Const CSLighterFlames As String = "CS_lighter_flames"
        Public Const CSPegBloodLoop As String = "CS_peg_blood_loop"
        Public Const CSPegBloodNose As String = "CS_peg_blood_nose"
        Public Const DestBanknotePile As String = "dest_banknote_pile"
        Public Const DestBinFastfood As String = "dest_bin_fastfood"
        Public Const DestBinHousehold As String = "dest_bin_household"
        Public Const DestBinStreet As String = "dest_bin_street"
        Public Const DestCeramic As String = "dest_ceramic"
        Public Const DestCeramicPlate As String = "dest_ceramic_plate"
        Public Const DestCeramicPlates As String = "dest_ceramic_plates"
        Public Const DestChips As String = "dest_chips"
        Public Const DestChipPacket As String = "dest_chip_packet"
        Public Const DestCoinPile As String = "dest_coin_pile"
        Public Const DestCrispbagFull As String = "dest_crispbag_full"
        Public Const DestDumpsters As String = "dest_dumpsters"
        Public Const DestElectrical As String = "dest_electrical"
        Public Const DestElectricalPlastic As String = "dest_electrical_plastic"
        Public Const DestFlowerLeaves As String = "dest_flower_leaves"
        Public Const DestFlowerPetals As String = "dest_flower_petals"
        Public Const DestFoodDebris As String = "dest_food_debris"
        Public Const DestFruitpileApples As String = "dest_fruitpile_apples"
        Public Const DestFruitpileBananas As String = "dest_fruitpile_bananas"
        Public Const DestFruitpileMix As String = "dest_fruitpile_mix"
        Public Const DestFruitpileOranges As String = "dest_fruitpile_oranges"
        Public Const DestFuelDump As String = "dest_fuel_dump"
        Public Const DestGlassBrownEmpty As String = "dest_glass_brown_empty"
        Public Const DestGlassClearDots As String = "dest_glass_clear_dots"
        Public Const DestGlassClearDust As String = "dest_glass_clear_dust"
        Public Const DestGlassClearEmpty As String = "dest_glass_clear_empty"
        Public Const DestGlassClearLager As String = "dest_glass_clear_lager"
        Public Const DestGlassClearRedwine As String = "dest_glass_clear_redwine"
        Public Const DestGlassClearShards As String = "dest_glass_clear_shards"
        Public Const DestGlassGreenEmpty As String = "dest_glass_green_empty"
        Public Const DestGlassLager As String = "dest_glass_lager"
        Public Const DestGlassPanes As String = "dest_glass_panes"
        Public Const DestGlassRedwine As String = "dest_glass_redwine"
        Public Const DestGlassWater As String = "dest_glass_water"
        Public Const DestJuiceCups As String = "dest_juice_cups"
        Public Const DestJuiceSplash As String = "dest_juice_splash"
        Public Const DestLightbulbDots As String = "dest_lightbulb_dots"
        Public Const DestLightbulbDust As String = "dest_lightbulb_dust"
        Public Const DestLightbulbGlass As String = "dest_lightbulb_glass"
        Public Const DestLightbulbGlow As String = "dest_lightbulb_glow"
        Public Const DestLightbulbOff As String = "dest_lightbulb_off"
        Public Const DestLightbulbOn As String = "dest_lightbulb_on"
        Public Const DestLightbulbSparks As String = "dest_lightbulb_sparks"
        Public Const DestMailBundle As String = "dest_mail_bundle"
        Public Const DestMetalObjects As String = "dest_metal_objects"
        Public Const DestMetalShards As String = "dest_metal_shards"
        Public Const DestMetalSlivers As String = "dest_metal_slivers"
        Public Const DestMetalSparks As String = "dest_metal_sparks"
        Public Const DestMoneyMixed As String = "dest_money_mixed"
        Public Const DestNapkinPieces As String = "dest_napkin_pieces"
        Public Const DestNewspaperBundle As String = "dest_newspaper_bundle"
        Public Const DestPaintPot As String = "dest_paint_pot"
        Public Const DestPaintPotGoop As String = "dest_paint_pot_goop"
        Public Const DestPaintPotMetal As String = "dest_paint_pot_metal"
        Public Const DestPigeonBlood As String = "dest_pigeon_blood"
        Public Const DestPigeonFluff As String = "dest_pigeon_fluff"
        Public Const DestPigeonMist As String = "dest_pigeon_mist"
        Public Const DestPlasterboard As String = "dest_plasterboard"
        Public Const DestPlastic As String = "dest_plastic"
        Public Const DestPlasticBrownCider As String = "dest_plastic_brown_cider"
        Public Const DestPlasticChunks As String = "dest_plastic_chunks"
        Public Const DestPlasticClearEmpty As String = "dest_plastic_clear_empty"
        Public Const DestPlasticClearWater As String = "dest_plastic_clear_water"
        Public Const DestPlasticDust As String = "dest_plastic_dust"
        Public Const DestPlasticSpecks As String = "dest_plastic_specks"
        Public Const DestSauceBottle As String = "dest_sauce_bottle"
        Public Const DestSodapileEcola As String = "dest_sodapile_ecola"
        Public Const DestSodapileGinger As String = "dest_sodapile_ginger"
        Public Const DestSodapileLemon As String = "dest_sodapile_lemon"
        Public Const DestSodapileMix As String = "dest_sodapile_mix"
        Public Const DestSodapileSprunk As String = "dest_sodapile_sprunk"
        Public Const DestSparkingSPAWNSparks As String = "dest_sparking_SPAWN_sparks"
        Public Const DestSparkingWires As String = "dest_sparking_wires"
        Public Const DestSparksFast As String = "dest_sparks_fast"
        Public Const DestStoneObjects As String = "dest_stone_objects"
        Public Const DestStonePillars As String = "dest_stone_pillars"
        Public Const DestStoneSlabs As String = "dest_stone_slabs"
        Public Const DestSweeties As String = "dest_sweeties"
        Public Const DestWood As String = "dest_wood"
        Public Const DestWoodCrate As String = "dest_wood_crate"
        Public Const DestWoodPlanks As String = "dest_wood_planks"
        Public Const DestWoodShards As String = "dest_wood_shards"
        Public Const ExplosionAAnim As String = "explosion_a_anim"
        Public Const ExplosionAirCarChunks As String = "exp_air_car_chunks"
        Public Const ExplosionBridgeExplosion As String = "exp_bridge_explosion"
        Public Const ExplosionChopperChase As String = "exp_chopper_chase"
        Public Const ExplosionFireball As String = "exp_fireball"
        Public Const ExplosionFireballAir As String = "exp_fireball_air"
        Public Const ExplosionFireballExplosion As String = "exp_fireball_explosion"
        Public Const ExplosionFireballLingeringsmoke As String = "exp_fireball_lingeringsmoke"
        Public Const ExplosionFireballSimpleglow As String = "exp_fireball_simpleglow"
        Public Const ExplosionFireballSmoke As String = "exp_fireball_smoke"
        Public Const ExplosionFireballSmokeRing As String = "exp_fireball_smokeRing"
        Public Const ExplosionGrenade As String = "exp_grenade"
        Public Const ExplosionGrenadeAir As String = "exp_grenade_air"
        Public Const ExplosionGrenadeCore As String = "exp_grenade_core"
        Public Const ExplosionGrenadeSmoke As String = "exp_grenade_smoke"
        Public Const ExplosionGrenadeSpikes As String = "exp_grenade_spikes"
        Public Const ExplosionMissedChopper As String = "exp_missed_chopper"
        Public Const ExplosionMolotov As String = "exp_molotov"
        Public Const ExplosionMolotovAir As String = "exp_molotov_air"
        Public Const ExplosionMolAirGlass As String = "exp_mol_air_glass"
        Public Const ExplosionMolAirSparks As String = "exp_mol_air_sparks"
        Public Const ExplosionMolExplosion As String = "exp_mol_explosion"
        Public Const ExplosionMolSimpleglow As String = "exp_mol_simpleglow"
        Public Const ExplosionPetrolBoom As String = "exp_petrol_boom"
        Public Const ExplosionPetrolBoomBack As String = "exp_petrol_boom_back"
        Public Const ExplosionPetrolBurst As String = "exp_petrol_burst"
        Public Const ExplosionPetrolChunks As String = "exp_petrol_chunks"
        Public Const ExplosionPetrolFlamingDebris As String = "exp_petrol_flaming_debris"
        Public Const ExplosionPetrolPump As String = "exp_petrol_pump"
        Public Const ExplosionPetrolSlivers As String = "exp_petrol_slivers"
        Public Const ExplosionPetrolSmoke As String = "exp_petrol_smoke"
        Public Const ExplosionPetrolSparks As String = "exp_petrol_sparks"
        Public Const ExplosionPetrolSpike As String = "exp_petrol_spike"
        Public Const ExplosionRiggedBoomUp As String = "exp_rigged_boom_up"
        Public Const ExplosionRiggedChunks As String = "exp_rigged_chunks"
        Public Const ExplosionRiggedSmoke As String = "exp_rigged_smoke"
        Public Const ExplosionRiggedSpikes As String = "exp_rigged_spikes"
        Public Const ExplosionRocket As String = "exp_rocket"
        Public Const ExplosionRocketAir As String = "exp_rocket_air"
        Public Const ExplosionShipDestroy As String = "exp_ship_destroy"
        Public Const ExplosionTrespassBoom As String = "exp_trespass_boom"
        Public Const ExplosionTrespassBoom2 As String = "exp_trespass_boom2"
        Public Const ExplosionTrespassCore As String = "exp_trespass_core"
        Public Const ExplosionTrespassCore2 As String = "exp_trespass_core2"
        Public Const ExplosionTrespassHuge As String = "exp_trespass_huge"
        Public Const ExplosionTrespassMid As String = "exp_trespass_mid"
        Public Const ExplosionTrespassUpper As String = "exp_trespass_upper"
        Public Const ExplosionUpper1SPAWN As String = "exp_upper1_SPAWN"
        Public Const ExplosionUpper2SPAWN As String = "exp_upper2_SPAWN"
        Public Const ExplosionUpper3SPAWN As String = "exp_upper3_SPAWN"
        Public Const ExplosionUpper4SPAWN As String = "exp_upper4_SPAWN"
        Public Const ExplosionUpper5SPAWN As String = "exp_upper5_SPAWN"
        Public Const ExpVehicle As String = "exp_vehicle"
        Public Const ExpVehicleAir As String = "exp_vehicle_air"
        Public Const FireBlastSpawned As String = "fire_blast_spawned"
        Public Const FireBlocksFlames As String = "fire_blocks_flames"
        Public Const FireBlocksRoad As String = "fire_blocks_road"
        Public Const FireBlocksSmoke As String = "fire_blocks_smoke"
        Public Const FireChopperTail As String = "fire_chopper_tail"
        Public Const FireGasBlastFlames As String = "fire_gas_blast_flames"
        Public Const FireGasBlastGlow As String = "fire_gas_blast_glow"
        Public Const FireGasBurner As String = "fire_gas_burner"
        Public Const FireGasBurnerFlames As String = "fire_gas_burner_flames"

        Public Const FireGasBurnerGlow As String = "fire_gas_burner_glow"
        Public Const FireGasBurnBlast As String = "fire_gas_burn_blast"
        Public Const FireGasIntermittent As String = "fire_gas_intermittent"
        Public Const FireHotdogBlaze As String = "fire_hotdog_blaze"
        Public Const FireObjectFlames As String = "fire_object_flames"
        Public Const FireObjectGlow As String = "fire_object_glow"
        Public Const FireObjectSmoke As String = "fire_object_smoke"
        Public Const FirePedBodyGlow As String = "fire_ped_body_glow"
        Public Const FirePedLimbGlow As String = "fire_ped_limb_glow"
        Public Const FirePedSmoking As String = "fire_ped_smoking"
        Public Const FirePlumeLarge As String = "fire_plume_large"
        Public Const FireTyreFlames As String = "fire_tyre_flames"
        Public Const FireVehicleSmoke As String = "fire_vehicle_smoke"
        Public Const GlassChunkSheet As String = "glass_chunk_sheet"
        Public Const GlassDotsSheet As String = "glass_dots_sheet"
        Public Const ImpactBulletArmour As String = "imp_bullet_armour"
        Public Const ImpactBulletCardboard As String = "imp_bullet_cardboard"
        Public Const ImpactBulletCarpet As String = "imp_bullet_carpet"
        Public Const ImpactBulletConcrete As String = "imp_bullet_concrete"
        Public Const ImpactBulletDefault As String = "imp_bullet_default"
        Public Const ImpactBulletDirtDry As String = "imp_bullet_dirt_dry"
        Public Const ImpactBulletGlass As String = "imp_bullet_glass"
        Public Const ImpactBulletGravel As String = "imp_bullet_gravel"
        Public Const ImpactBulletLeaves As String = "imp_bullet_leaves"
        Public Const ImpactBulletMattressFoam As String = "imp_bullet_mattress_foam"
        Public Const ImpactBulletMetal As String = "imp_bullet_metal"
        Public Const ImpactBulletMudSoft As String = "imp_bullet_mud_soft"
        Public Const ImpactBulletPaper As String = "imp_bullet_paper"
        Public Const ImpactBulletPillowFeathers As String = "imp_bullet_pillow_feathers"
        Public Const ImpactBulletSand As String = "imp_bullet_sand"
        Public Const ImpactBulletTvscreen As String = "imp_bullet_tvscreen"
        Public Const ImpactBulletVideowall As String = "imp_bullet_videowall"
        Public Const ImpactBulletWater As String = "imp_bullet_water"
        Public Const ImpactBulletWood As String = "imp_bullet_wood"
        Public Const ImpactExpConcrete As String = "imp_exp_concrete"
        Public Const ImpactExpMetal As String = "imp_exp_metal"
        Public Const ImpactExpMetalCore As String = "imp_exp_metal_core"
        Public Const ImpactExpWood As String = "imp_exp_wood"
        Public Const ImpactExpWoodCore As String = "imp_exp_wood_core"
        Public Const ImpactGlassShards As String = "imp_glass_shards"
        Public Const ImpactLeavesFalling As String = "imp_leaves_falling"
        Public Const ImpactMeleeConcrete As String = "imp_melee_concrete"
        Public Const ImpactMeleeGlass As String = "imp_melee_glass"
        Public Const ImpactMeleeWood As String = "imp_melee_wood"
        Public Const ImpactShotgunGlass As String = "imp_shotgun_glass"
        Public Const ImpactShotgunWater As String = "imp_shotgun_water"
        Public Const LeavesFallinginwind As String = "leaves_fallinginwind"
        Public Const LeavesWindyAutumnal As String = "leaves_windy_autumnal"
        Public Const LeavesWindyPale As String = "leaves_windy_pale"
        Public Const LeavesWindAutumnal As String = "leaves_wind_autumnal"
        Public Const LeavesWindPale As String = "leaves_wind_pale"
        Public Const MetalChunkSheet As String = "metal_chunk_sheet"
        Public Const MetalShardSpec As String = "metal_shard_spec"
        Public Const CardboardFlapA As String = "Cardboard_Flap_A"
        Public Const CardboardFlapB As String = "Cardboard_Flap_B"
        Public Const CardboardPieces As String = "cardboard_pieces"
        Public Const ChinaChunksSheet As String = "china_chunks_sheet"
        Public Const CockroachesAnim As String = "cockroaches_anim"
        Public Const DiscoIce As String = "disco_ice"
        Public Const DrawScreenspace As String = "draw_screenspace"
        Public Const GrainyDirtSheet As String = "grainy_dirt_sheet"
        Public Const GravelChunkSheet As String = "gravel_chunk_sheet"
        Public Const GravelLotsSheet As String = "gravel_lots_sheet"
        Public Const InteriorGunsmoke As String = "interior_gunsmoke"
        Public Const NormalSphere128 As String = "normal_sphere_128"
        Public Const PlayerWastedCash As String = "player_wasted_cash"
        Public Const RaindropBlurred As String = "raindrop_blurred"
        Public Const MultiObjects01 As String = "multi_objects_01"
        Public Const MultiObjects02 As String = "multi_objects_02"
        Public Const MultiObjects03 As String = "multi_objects_03"
        Public Const MuzzleLauncherSmoke As String = "muz_launcher_smoke"
        Public Const MuzzleMachine As String = "muz_machine"
        Public Const MuzzleMachineCore As String = "muz_machine_core"
        Public Const MuzzleMachineFront As String = "muz_machine_front"
        Public Const MuzzleMachineGlow As String = "muz_machine_glow"
        Public Const MuzzleMinigun As String = "muz_minigun"
        Public Const MuzzleMinigunSmoke As String = "muz_minigun_smoke"
        Public Const MuzzlePistolLarge As String = "muz_pistol_large"
        Public Const MuzzlePistolSmall As String = "muz_pistol_small"
        Public Const MuzzlePistolSmoke As String = "muz_pistol_smoke"
        Public Const MuzzleRocket As String = "muz_rocket"
        Public Const MuzzleRocketFront As String = "muz_rocket_front"
        Public Const MuzzleRocketSmoke As String = "muz_rocket_smoke"
        Public Const MuzzleShotgun As String = "muz_shotgun"
        Public Const MuzzleShotgunCore As String = "muz_shotgun_core"
        Public Const MuzzleShotgunGlow As String = "muz_shotgun_glow"
        Public Const MuzzleShotgunSmoke As String = "muz_shotgun_smoke"
        Public Const MuzzleShotgunSparks As String = "muz_shotgun_sparks"
        Public Const MuzzleSmg As String = "muz_smg"
        Public Const OverhangDrips10m As String = "overhang_drips_10m"
        Public Const OverhangDrips1m As String = "overhang_drips_1m"
        Public Const OverhangDrips2m As String = "overhang_drips_2m"
        Public Const OverhangDrips5m As String = "overhang_drips_5m"
        Public Const OverhangDripsSpawner As String = "overhang_drips_spawner"
        Public Const OverhangLittledrips10m As String = "overhang_littledrips_10m"
        Public Const OverhangLittledrips1m As String = "overhang_littledrips_1m"
        Public Const OverhangLittledrips2m As String = "overhang_littledrips_2m"
        Public Const OverhangLittledrips5m As String = "overhang_littledrips_5m"
        Public Const PedExhaleLinger As String = "ped_exhale_linger"
        Public Const PedExhaleVapour As String = "ped_exhale_vapour"
        Public Const PedFootDirtDry As String = "ped_foot_dirt_dry"
        Public Const PedFootGravel As String = "ped_foot_gravel"
        Public Const PedFootLeaves As String = "ped_foot_leaves"
        Public Const PedFootMudDust As String = "ped_foot_mud_dust"
        Public Const PedFootMudSoft As String = "ped_foot_mud_soft"
        Public Const PedFootSand As String = "ped_foot_sand"
        Public Const PedFootWater As String = "ped_foot_water"
        Public Const PedFootWaterL As String = "ped_foot_water_L"
        Public Const PedPissingMist As String = "ped_pissing_mist"
        Public Const PedSmokeExhale As String = "ped_smoke_exhale"

        Public Const Qub3DExplodeDust As String = "qub_explode_dust"
        Public Const Qub3DExplodeGlow As String = "qub_explode_glow"
        Public Const Qub3DExplodeRings As String = "qub_explode_rings"
        Public Const Qub3DExplodeSparks As String = "qub_explode_sparks"
        Public Const Qub3DExplodeStreaks As String = "qub_explode_streaks"
        Public Const Qub3DLargeExplodeBlue As String = "qub_lg_explode_blue"
        Public Const Qub3DLargeExplodeGreen As String = "qub_lg_explode_green"
        Public Const Qub3DLargeExplodeOrange As String = "qub_lg_explode_orange"
        Public Const Qub3DLargeExplodePurple As String = "qub_lg_explode_purple"
        Public Const Qub3DLargeExplodeRed As String = "qub_lg_explode_red"
        Public Const Qub3DLargeExplodeYellow As String = "qub_lg_explode_yellow"
        Public Const Qub3DMergeOrange As String = "qub_merge_orange"
        Public Const Qub3DMergePurple As String = "qub_merge_purple"
        Public Const Qub3DMergeSparks As String = "qub_merge_sparks"
        Public Const Qub3DMergeYellow As String = "qub_merge_yellow"
        Public Const Qub3DSmallExplodeBlue As String = "qub_sm_explode_blue"
        Public Const Qub3DSmallExplodeGreen As String = "qub_sm_explode_green"
        Public Const Qub3DSmallExplodeOrange As String = "qub_sm_explode_orange"
        Public Const Qub3DSmallExplodePurple As String = "qub_sm_explode_purple"
        Public Const Qub3DSmallExplodeRed As String = "qub_sm_explode_red"
        Public Const Qub3DSmallExplodeYellow As String = "qub_sm_explode_yellow"
        Public Const ScrapeBarkShards As String = "scrape_bark_shards"
        Public Const ScrapeCarpet As String = "scrape_carpet"
        Public Const ScrapeCarpetDust As String = "scrape_carpet_dust"
        Public Const ScrapeDusty As String = "scrape_dusty"
        Public Const ScrapeLeaves3D As String = "scrape_leaves_3D"
        Public Const ScrapeMudSpecks As String = "scrape_mud_specks"
        Public Const ScrapeWoodShards As String = "scrape_wood_shards"
        Public Const ShotChemicalGlug As String = "shot_chemical_glug"
        Public Const ShotDirectedChem As String = "shot_directed_chem"
        Public Const ShotDirectedChemCore As String = "shot_directed_chem_core"
        Public Const ShotDirectedFlame As String = "shot_directed_flame"
        Public Const ShotDirectedOil As String = "shot_directed_oil"
        Public Const ShotDirectedOilCore As String = "shot_directed_oil_core"
        Public Const ShotDirectedSteam As String = "shot_directed_steam"
        Public Const ShotDirectedSteamCore As String = "shot_directed_steam_core"
        Public Const ShotDirectedSteamLinger As String = "shot_directed_steam_linger"
        Public Const ShotDirectedWater As String = "shot_directed_water"
        Public Const ShotDirectedWaterCore As String = "shot_directed_water_core"
        Public Const ShotGasCanister As String = "shot_gas_canister"
        Public Const ShotGasExplosion As String = "shot_gas_explosion"
        Public Const ShotOilGlug As String = "shot_oil_glug"
        Public Const ShotPlasterboard As String = "shot_plasterboard"
        Public Const ShotWaterGlug As String = "shot_water_glug"
        Public Const ShotWaterTower As String = "shot_water_tower"
        Public Const ShotWaterTowerCore As String = "shot_water_tower_core"
        Public Const SmokeChimneySheet As String = "smoke_chimney_sheet"
        Public Const SmokeCloudAnim As String = "smoke_cloud_anim"
        Public Const SmokeFilledCar As String = "smoke_filled_car"
        Public Const SmokeNewPlumes As String = "smoke_new_plumes"
        Public Const SmokeOnlyCinders As String = "smoke_only_cinders"
        Public Const SmokeOnlyFlames As String = "smoke_only_flames"
        Public Const SmokeOnlySmoke As String = "smoke_only_smoke"
        Public Const SmokePlumeFloat As String = "smoke_plume_float"
        Public Const SmokePlumeWindow As String = "smoke_plume_window"
        Public Const SmokeVaultLingers As String = "smoke_vault_lingers"
        Public Const SparksArcingAnim As String = "sparks_arcing_anim"
        Public Const VehicleBackfireGlow As String = "veh_backfire_glow"
        Public Const VehicleExhaustBanger As String = "veh_exhaust_banger"
        Public Const VehicleExhaustCore As String = "veh_exhaust_core"
        Public Const VehicleExhaustFront As String = "veh_exhaust_front"
        Public Const VehicleExhaustTruck As String = "veh_exhaust_truck"
        Public Const VehicleHeadlightDots As String = "veh_headlight_dots"
        Public Const VehicleHeadlightDust As String = "veh_headlight_dust"
        Public Const VehicleHeliDownwash As String = "veh_heli_downwash"
        Public Const VehicleHeliTailDust As String = "veh_heli_tail_dust"
        Public Const VehiclePetroltankCar As String = "veh_petroltank_car"
        Public Const VehiclePlumeRising As String = "veh_plume_rising"
        Public Const VehicleRespraySmoke As String = "veh_respray_smoke"
        Public Const VehicleRimDispConc As String = "veh_rim_disp_conc"
        Public Const VehicleTrainSparks As String = "veh_train_sparks"
        Public Const VehicleTyrePuncture As String = "veh_tyre_puncture"
        Public Const VehicleWreckedBike As String = "veh_wrecked_bike"
        Public Const VehicleWreckedBoat As String = "veh_wrecked_boat"
        Public Const VehicleWreckedFlames As String = "veh_wrecked_flames"
        Public Const VehicleWreckedHeli As String = "veh_wrecked_heli"
        Public Const VehicleWreckedLinger As String = "veh_wrecked_linger"
        Public Const VehicleWreckedSmoke As String = "veh_wrecked_smoke"
        Public Const VehicleWreckedTruck As String = "veh_wrecked_truck"
        Public Const WaterBoatEntry As String = "water_boat_entry"
        Public Const WaterBoatEntryL As String = "water_boat_entry_L"
        Public Const WaterBoatEntryR As String = "water_boat_entry_R"
        Public Const WaterCarwashDrips As String = "water_carwash_drips"
        Public Const WaterCarwashDripsDroplets As String = "water_carwash_drips_droplets"
        Public Const WaterCarwashDripsSpawnpoints As String = "water_carwash_drips_spawnpoints"
        Public Const WaterCarwashJets As String = "water_carwash_jets"
        Public Const WaterCarwashMist As String = "water_carwash_mist"
        Public Const WaterCarwashSpawn As String = "water_carwash_spawn"
        Public Const WaterCarwashSpit As String = "water_carwash_spit"
        Public Const WaterCarwashSpray As String = "water_carwash_spray"
        Public Const WaterCasinoDrop As String = "water_casino_drop"
        Public Const WaterCastleDir As String = "water_castle_dir"
        Public Const WaterCastleDrop As String = "water_castle_drop"
        Public Const WaterCastleJet As String = "water_castle_jet"
        Public Const WaterCentralDrop As String = "water_central_drop"
        Public Const WaterCityhallDir As String = "water_cityhall_dir"
        Public Const WaterCornerJet As String = "water_corner_jet"
        Public Const WaterDripsSheet As String = "water_drips_sheet"
        Public Const WaterFountain5th As String = "water_fountain_5th"
        Public Const WaterFountainCastleLow As String = "water_fountain_castle_low"
        Public Const WaterFountainCastleUp As String = "water_fountain_castle_up"
        Public Const WaterFountainCentral As String = "water_fountain_central"
        Public Const WaterFountainCityhall As String = "water_fountain_cityhall"
        Public Const WaterFountainCorners As String = "water_fountain_corners"
        Public Const WaterFountainDirectional As String = "water_fountain_directional"
        Public Const WaterFountainJet As String = "water_fountain_jet"
        Public Const WaterFountainPour As String = "water_fountain_pour"
        Public Const WaterFountainRock As String = "water_fountain_rock"
        Public Const WaterFountainSpout As String = "water_fountain_spout"
        Public Const WaterFountainSpray As String = "water_fountain_spray"
        Public Const WaterFountainTier As String = "water_fountain_tier"
        Public Const WaterFountainTierL As String = "water_fountain_tier_L"
        Public Const WaterGenericDir As String = "water_generic_dir"
        Public Const WaterGenericJet As String = "water_generic_jet"
        Public Const WaterHeliBlades As String = "water_heli_blades"
        Public Const WaterHoseSpray As String = "water_hose_spray"
        Public Const WaterHydrantDir As String = "water_hydrant_dir"
        Public Const WaterHydrantJet As String = "water_hydrant_jet"
        Public Const WaterHydrantSide As String = "water_hydrant_side"
        Public Const WaterHydrantSP As String = "water_hydrant_SP"
        Public Const WaterHydrantTop As String = "water_hydrant_top"
        Public Const WaterHydrantVerticalJet As String = "water_hydrant_vertical_jet"
        Public Const WaterJetsMisty As String = "water_jets_misty"
        Public Const WaterPipeBubble As String = "water_pipe_bubble"
        Public Const WaterPipeBubble2 As String = "water_pipe_bubble2"
        Public Const WaterPipeCasino As String = "water_pipe_casino"
        Public Const WaterPipeFlow As String = "water_pipe_flow"
        Public Const WaterRockBubble As String = "water_rock_bubble"
        Public Const WaterRockBubble2 As String = "water_rock_bubble2"
        Public Const WaterSplashesSheet As String = "water_splashes_sheet"
        Public Const WaterSplashCam As String = "water_splash_cam"
        Public Const WaterSplashPed As String = "water_splash_ped"
        Public Const WaterTierSpray As String = "water_tier_spray"
        Public Const WaterVehicleRing As String = "water_vehicle_ring"
        Public Const WeaponEjectedPistol As String = "weap_ejected_pistol"
        Public Const WeaponEjectedRifle As String = "weap_ejected_rifle"
        Public Const WeaponEjectedShotgun As String = "weap_ejected_shotgun"
        Public Const WeaponEjectedSmg As String = "weap_ejected_smg"
        Public Const WeaponGlowSpikeL As String = "weap_glow_spike_L"
        Public Const WeaponMolotovFlame As String = "weap_molotov_flame"
        Public Const WeaponMolotovGlow As String = "weap_molotov_glow"
        Public Const WeaponMolotovSmoke As String = "weap_molotov_smoke"
        Public Const WeaponMolotovTrail As String = "weap_molotov_trail"
        Public Const WeaponRocketGlow As String = "weap_rocket_glow"
        Public Const WeaponRocketPlayer As String = "weap_rocket_player"
        Public Const WeaponRocketSmoke As String = "weap_rocket_smoke"
        Public Const WeaponBulletSmoke As String = "wpn_bullet_smoke"
        Public Const WeaponBulletTrace As String = "wpn_bullet_trace"
        Public Const WheelBurnoutDirt As String = "wheel_burnout_dirt"
        Public Const WheelBurnoutPool As String = "wheel_burnout_pool"
        Public Const WheelDispConcRim As String = "wheel_disp_conc_rim"
        Public Const WheelDispGrass As String = "wheel_disp_grass"
        Public Const WheelDispGravel As String = "wheel_disp_gravel"
        Public Const WheelDispGravelW As String = "wheel_disp_gravel_w"
        Public Const WheelDispHardRim As String = "wheel_disp_hard_rim"
        Public Const WheelDispHardW As String = "wheel_disp_hard_w"
        Public Const WheelDispLeaves As String = "wheel_disp_leaves"
        Public Const WheelDispLeavesW As String = "wheel_disp_leaves_w"
        Public Const WheelDispMud As String = "wheel_disp_mud"
        Public Const WheelDispWoodRim As String = "wheel_disp_wood_rim"
        Public Const WheelFrictionConcRim As String = "wheel_friction_conc_rim"
        Public Const WheelFrictionDirtDry As String = "wheel_friction_dirt_dry"
        Public Const WheelFrictionDirtDryRim As String = "wheel_friction_dirt_dry_rim"
        Public Const WheelFrictionGrass As String = "wheel_friction_grass"
        Public Const WheelFrictionGravel As String = "wheel_friction_gravel"
        Public Const WheelFrictionGravelRim As String = "wheel_friction_gravel_rim"
        Public Const WheelFrictionHard As String = "wheel_friction_hard"
        Public Const WheelFrictionHardRim As String = "wheel_friction_hard_rim"
        Public Const WheelFrictionHardW As String = "wheel_friction_hard_w"
        Public Const WheelFrictionLeaves As String = "wheel_friction_leaves"
        Public Const WheelFrictionLeavesW As String = "wheel_friction_leaves_w"
        Public Const WheelFrictionMud As String = "wheel_friction_mud"
        Public Const WheelFrictionSand As String = "wheel_friction_sand"
        Public Const WheelFrictionSandRim As String = "wheel_friction_sand_rim"
        Public Const WheelFrictionWater As String = "wheel_friction_water"
        Public Const WheelFrictionWoodRim As String = "wheel_friction_wood_rim"
        Public Const WheelGravelLots As String = "Wheel_Gravel_Lots"
        Public Const WheelSandBurnout As String = "wheel_sand_burnout"
        Public Const WindDebrisLeaves As String = "wind_debris_leaves"
        Public Const WindDebrisMail As String = "wind_debris_mail"
        Public Const WindDebrisPaper As String = "wind_debris_paper"
    End Structure
    'Public Class Helper
    '    Public Structure Keys
    '        Public Shared MoveForward As Keys
    '        Public Shared MoveBackward As Keys
    '        Public Shared MoveUp As Keys
    '        Public Shared MoveDown As Keys
    '        Public Shared MoveLeft As Keys
    '        Public Shared MoveRight As Keys
    '        Public Shared NextEffect As Keys
    '        Public Shared PreviousEffect As Keys
    '        Public Shared IncreaseSize As Keys
    '        Public Shared DecreaseSize As Keys
    '        Public Shared RotateYawLeft As Keys
    '        Public Shared RotateYawRight As Keys
    '        Public Shared RotatePitchUp As Keys
    '        Public Shared RotatePitchDown As Keys
    '        Public Shared RotateRollLeft As Keys
    '        Public Shared RotateRollRight As Keys
    '    End Structure

    'End Class
End Class